M48
; DRILL file {KiCad (6.0.1)} date Sun Feb 19 21:21:00 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-02-19T21:21:00+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C14.000
%
G90
G05
T1
X120.33Y-165.78
X120.33Y-174.58
T2
X45.72Y-104.14
X45.72Y-170.18
X355.6Y-104.14
X355.6Y-170.18
T3
X330.2Y-170.18
T0
M30
